### ISSUE TITLE
Fix links between pages

### ISSUE THREAD

**Issue by zeckson** [freeridersochi/shop_php#12]
Check all links to external pages and fix links correctly.
For example:
1. Link from `login_page.php` to reistration page lead to `registrationPage.html` and currently is broken.
2. `category.php` instead of `product.php`
3. Check all admin pages menu

**Comment by freeridersochi** [comment]
Done!

**Comment by zeckson** [comment]
Не вижу коммита =(

**Comment by zeckson** [comment]
Ага, всё увидел — 3dedbf4eff5957874da71b16303c740227497749
