### ISSUE TITLE
Add orders table to database

### ISSUE THREAD

**Issue by zeckson** [freeridersochi/shop_php#25]
After successful checkout we need to create order with number and info with status to be able to fill this info in `personal_area` 
![image](https://user-images.githubusercontent.com/259739/64242987-3a3c4c00-cf0f-11e9-9631-bbd85e14c5f3.png)

**Comment by freeridersochi** [comment]
Тоже понятно.

**Comment by freeridersochi** [comment]
CREATE TABLE orders(
    id INT PRIMARY KEY AUTO_INCREMENT,
    number CHAR(255) NOT NULL,
    cost CHAR(255) NOT NULL UNIQUE,
    status CHAR(255),
    time CHAR(255),   
);
сделал так.
