### ISSUE TITLE
Add promos to home.php

### ISSUE THREAD

**Issue by zeckson** [freeridersochi/shop_php#26]
Replace fake promos with real ones:
![image](https://user-images.githubusercontent.com/259739/64243261-be8ecf00-cf0f-11e9-8578-6437340e43e8.png)
![image](https://user-images.githubusercontent.com/259739/64243270-c484b000-cf0f-11e9-8e19-9e95671017ad.png)

**Comment by freeridersochi** [comment]
Понятно. Буду заниматься.

**Comment by freeridersochi** [comment]
created
